ipam:
  mode: kubernetes

kubeProxyReplacement: false

authentication:
  enabled: true
  mutual:
    spire:
      enabled: true
      install:
        enabled: true
        server:
          dataStorage:
            enabled: false

hubble:
  enabled: true
  relay:
    enabled: true
  ui:
    enabled: true

operator:
  replicas: 1

image:
  pullPolicy: IfNotPresent
