apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: hubble-l7-visibility
  namespace: app
spec:
  endpointSelector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - frontend
          - frontend-traffic
  egress:
    - toEndpoints:
        - matchLabels:
            k8s:io.kubernetes.pod.namespace: kube-system
            k8s:k8s-app: kube-dns
      toPorts:
        - ports:
            - port: "53"
              protocol: ANY
          rules:
            dns:
              - matchPattern: "*"
    - toEndpoints:
        - matchLabels:
            k8s:io.kubernetes.pod.namespace: app
      toPorts:
        - ports:
            - port: "80"
              protocol: TCP
            - port: "8080"
              protocol: TCP
          rules:
            http:
              - {}
